const API='/api';const token=()=>localStorage.getItem('studly_token');
async function api(path,opts={}){const headers=opts.headers||{};if(token())headers.Authorization='Bearer '+token();if(opts.body&&!(opts.body instanceof FormData))headers['Content-Type']='application/json';const r=await fetch(API+path,{...opts,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'เกิดข้อผิดพลาด');return d}
function toast(msg,ok=false){const el=document.getElementById('toast');if(el){el.textContent=msg;el.style.color=ok?'#16a34a':'#dc2626';setTimeout(()=>el.textContent='',3500)}}
async function login(e){e.preventDefault();try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email:document.getElementById('email').value,password:document.getElementById('password').value})});localStorage.setItem('studly_token',d.token);location.href=d.user.role==='student'?'student.html':'teacher.html'}catch(err){toast(err.message)}}
if(document.getElementById('loginForm'))document.getElementById('loginForm').addEventListener('submit',login);
async function guard(role){try{const d=await api('/me');if(d.user.role!==role){location.href=d.user.role==='student'?'student.html':'teacher.html';return null}return d.user}catch(e){location.href='index.html';return null}}
async function logout(){await api('/auth/logout',{method:'POST'}).catch(()=>{});localStorage.removeItem('studly_token');location.href='index.html'}
function esc(x){return String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function statusBadge(s){const m={GRADED:['🟢 ตรวจและให้คะแนนเรียบร้อย','b-green'],SUBMITTED:['🔵 ส่งแล้ว รออาจารย์ตรวจ','b-blue'],NOT_SUBMITTED:['⚪ ยังไม่ได้ส่ง','b-gray'],OVERDUE:['🔴 เลยกำหนด','b-red'],NOT_RECEIVED:['⚫ ไม่ได้รับงาน','b-gray']};const x=m[s]||[s,'b-gray'];return `<span class="badge ${x[1]}">${x[0]}</span>`}
function shell(user,role){document.getElementById('app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">STUDLY<small>Your AI Study Buddy</small></div><div class="nav" id="nav"></div></aside><main class="main"><div class="topbar"><div><h2 id="pageTitle">Dashboard</h2><div class="muted">AI Early Warning & Learning Support System</div></div><div class="user-pill">${esc(user.name)} · ${role==='student'?'นักเรียน':'ครู'} <button class="btn gray" onclick="logout()">ออกจากระบบ</button></div></div><div id="content"></div></main></div>`}
window.api=api;window.guard=guard;window.logout=logout;window.toast=toast;window.esc=esc;window.statusBadge=statusBadge;window.shell=shell;
