let selectedSubject='';
(async()=>{const user=await guard('student');if(!user)return;shell(user,'student');const nav=[['dashboard','หน้าหลัก'],['subjects','รายวิชา'],['assignments','งานของฉัน'],['planner','AI Study Planner'],['risk','คะแนนและความเสี่ยง'],['notifications','การแจ้งเตือน'],['profile','ข้อมูลส่วนตัว / ตั้งค่า']];document.getElementById('nav').innerHTML=nav.map((x,i)=>`<button class="${i===0?'active':''}" data-sec="${x[0]}"><span>${x[1]}</span></button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>show(b.dataset.sec));await show('dashboard');})();
async function show(sec){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.sec===sec));const title={dashboard:'หน้าหลัก',subjects:'รายวิชา',assignments:'งานของฉัน',planner:'AI Study Planner',risk:'คะแนนและความเสี่ยง',notifications:'การแจ้งเตือน',profile:'ข้อมูลส่วนตัว / ตั้งค่า'}[sec];document.getElementById('pageTitle').textContent=title;const c=document.getElementById('content');try{
if(sec==='dashboard'){const d=await api('/student/dashboard');c.innerHTML=`<div class="grid stats"><div class="card stat"><div class="muted">คะแนนเฉลี่ย</div><div class="num">${d.summary.average}%</div></div><div class="card stat"><div class="muted">งานที่ต้องส่ง</div><div class="num">${d.summary.required}</div></div><div class="card stat"><div class="muted">งานใกล้ Deadline</div><div class="num">${d.summary.near}</div></div><div class="card stat"><div class="muted">Learning Risk</div><div class="num">${d.summary.risk==='HIGH'?'🔴 HIGH':'🟡 '+d.summary.risk}</div></div></div><div class="grid cards" style="margin-top:18px"><div class="card"><div class="row"><h3>สวัสดี, สมชาย 👋</h3><span class="badge b-red">Learning Risk: HIGH</span></div><p class="muted">STUDLY วิเคราะห์จาก Deadline, คะแนน และงานที่ค้าง เพื่อช่วยตัดสินใจว่าวันนี้ควรทำอะไรต่อ</p><button class="btn" onclick="show('planner')">ดู AI Study Plan →</button></div><div class="card ai-card"><h3>🥇 งานที่ควรทำก่อน</h3><div id="dashPriority">กำลังวิเคราะห์...</div></div></div>`;const ai=await api('/ai/student');document.getElementById('dashPriority').innerHTML=ai.items.slice(0,2).map(x=>`<div style="margin:12px 0"><div class="priority">${esc(x.title)} <span class="badge ${x.priority.level==='HIGH'?'b-red':x.priority.level==='MEDIUM'?'b-yellow':'b-green'}">${x.priority.level}</span></div><div class="muted">${esc(x.priority.reasons.join(' · '))}</div></div>`).join('')}
else if(sec==='subjects'){const d=await api('/student/dashboard');c.innerHTML=`<div class="grid cards">${d.subjects.map(s=>`<button class="card subject-card" style="text-align:left;border:0;cursor:pointer" onclick="showSubject('${esc(s.name)}')"><div class="row"><h3>${esc(s.name)}</h3>${s.risk==='HIGH'?'<span class="badge b-red">🔴 High Risk</span>':s.risk==='MEDIUM'?'<span class="badge b-yellow">🟡 Medium Risk</span>':'<span class="badge b-green">🟢 Low Risk</span>'}</div><div style="font-size:34px;font-weight:900">${s.score}%</div><div class="muted">คะแนนปัจจุบัน · ${d.assignments.filter(a=>a.subject===s.name).length} Assignment · คลิกเพื่อดูงานวิชานี้</div></button>`).join('')}</div>`}
else if(sec==='assignments'){const d=await api('/assignments');const list=selectedSubject?d.assignments.filter(a=>a.subject===selectedSubject):d.assignments;c.innerHTML=`<div class="card"><div class="row"><div><h3>งานของฉัน${selectedSubject?` · ${esc(selectedSubject)}`:''}</h3><div class="muted">${selectedSubject?'แสดงเฉพาะ Assignment ของวิชานี้':'แสดง Assignment ทั้งหมด'}</div></div>${selectedSubject?'<button class="btn gray" onclick="clearSubjectFilter()">ดูทุกวิชา</button>':''}</div><div class="table-wrap"><table class="table"><thead><tr><th>งาน</th><th>วิชา</th><th>ประเภท</th><th>Deadline</th><th>คะแนน</th><th>สถานะ</th><th></th></tr></thead><tbody>${list.length?list.map(a=>`<tr><td><b>${esc(a.title)}</b><div class="muted">${esc(a.description)}</div></td><td>${esc(a.subject)}</td><td>${a.type}</td><td>${new Date(a.deadline).toLocaleString('th-TH')}</td><td>${a.maxScore}</td><td>${statusBadge(a.status)}</td><td><div class="actions">${a.attachment?.url?`<button class="btn gray" onclick="openFile('${esc(a.attachment.url)}')">👁 ไฟล์โจทย์</button>`:''}<button class="btn" onclick="${a.status==='GRADED'?`openResult('${a.id}')`:`openSubmit('${a.id}','${a.type}')`}">${a.status==='GRADED'?'ดูผล':'เปิดงาน'}</button></div></td></tr>`).join(''):'<tr><td colspan="7" class="empty">ยังไม่มี Assignment ในวิชานี้</td></tr>'}</tbody></table></div></div>`}
else if(sec==='planner'){const d=await api('/ai/student');c.innerHTML=`<div class="grid cards">${d.items.map((x,i)=>`<div class="card ai-card"><div class="row"><h3>${i+1}. ${esc(x.title)}</h3><span class="badge ${x.priority.level==='HIGH'?'b-red':x.priority.level==='MEDIUM'?'b-yellow':'b-green'}">${x.priority.level}</span></div><h2>${x.estimatedTime} นาที</h2><p><b>เหตุผล:</b> ${esc(x.priority.reasons.join(' · ')||'งานนี้มีความสำคัญตามข้อมูลปัจจุบัน')}</p><div class="muted">Risk: ${x.risk} · Deadline: ${new Date(x.deadline).toLocaleString('th-TH')}</div></div>`).join('')}</div>`}
else if(sec==='risk'){const d=await api('/student/dashboard');c.innerHTML=`<div class="grid cards">${d.subjects.map(s=>`<div class="card"><div class="row"><h3>${s.name}</h3>${s.risk==='HIGH'?'<span class="badge b-red">🔴 High Risk</span>':s.risk==='MEDIUM'?'<span class="badge b-yellow">🟡 Medium Risk</span>':'<span class="badge b-green">🟢 Low Risk</span>'}</div><p>คะแนนปัจจุบัน <b>${s.score}%</b></p><p class="muted">ระบบประเมินจาก Current Score + Pending Assignment + Deadline + Submission History</p></div>`).join('')}</div>`}
else if(sec==='notifications'){const d=await api('/notifications');c.innerHTML=`<div class="grid cards"><div class="card"><h3>การแจ้งเตือนล่าสุด</h3>${d.notifications.length?d.notifications.map(n=>`<div style="padding:14px 0;border-bottom:1px solid #eee"><b>${esc(n.title)}</b><div class="muted">${esc(n.message)}</div></div>`).join(''):'<div class="empty">ยังไม่มีการแจ้งเตือน</div>'}</div><div class="card"><h3>🔔 ตั้งค่าการแจ้งเตือน</h3><p class="muted">เลือกเปิด/ปิดสิ่งที่ต้องการรับ</p><div id="studentNotifyPageSettings">กำลังโหลด...</div></div></div>`;loadStudentNotifyBox('studentNotifyPageSettings')}
else if(sec==='profile'){const d=await api('/parent/status');const m=await api('/me');c.innerHTML=`<div class="grid cards"><div class="card"><h3>ข้อมูลส่วนตัว</h3><p>ชื่อ: <b>${esc(m.user.name)}</b></p><p>รหัสนักเรียน: ${m.user.studentId}</p><p>Email: ${m.user.email}</p><p>โรงเรียน: ${m.user.school}</p><p>ห้องเรียน: ${m.user.classroom}</p><p>ระดับชั้น: ${m.user.gradeLevel}</p></div><div class="card"><h3>👨‍👩‍👧 ผู้ปกครอง</h3><p>สถานะ LINE: ${d.connected?'<span class="badge b-green">🟢 เชื่อมต่อแล้ว</span>':'<span class="badge b-red">🔴 ยังไม่ได้เชื่อมต่อ</span>'}</p>${d.connected?`<p class="muted">ระบบสามารถส่ง Smart Alert ผ่าน LINE ได้</p><div class="actions"><button class="btn" onclick="testLine()">ส่งข้อความทดสอบ</button><button class="btn" onclick="smartAlert()">ส่ง Smart Alert Demo</button><button class="btn red" onclick="disconnectLine()">ยกเลิกการเชื่อมต่อ</button></div>`:`<p class="muted">เชื่อมต่อ LINE ของผู้ปกครองเพื่อรับ Smart Alert เมื่อ AI พบความเสี่ยงด้านการเรียน</p><button class="btn" onclick="generateLink()">+ เชื่อมต่อ LINE ผู้ปกครอง</button><div id="linkBox"></div>`}</div><div class="card"><h3>ตั้งค่าการแจ้งเตือน</h3><p class="muted">เลือกเปิด/ปิดการแจ้งเตือนที่ต้องการรับ</p><div id="studentNotifySettings">กำลังโหลด...</div></div></div>`;loadStudentNotificationSettings()}}
catch(e){c.innerHTML=`<div class="card"><b>เกิดข้อผิดพลาด:</b> ${esc(e.message)}</div>`}}
function showSubject(subject){selectedSubject=subject;show('assignments')}
function clearSubjectFilter(){selectedSubject='';show('assignments')}
async function openResult(id){try{const d=await api('/student/dashboard');const a=d.assignments.find(x=>x.id===id);const s=d.submissions.find(x=>x.assignmentId===id);if(!a||!s){toast('ไม่พบผลการส่งงาน');return}const modal=document.createElement('div');modal.className='modal-backdrop';modal.id='modal';modal.innerHTML=`<div class="modal"><button class="close" onclick="document.getElementById('modal').remove()">×</button><h2>${esc(a.title)}</h2><p>${esc(a.description)}</p><p><b>${esc(a.subject)}</b> · ${a.maxScore} คะแนน · Deadline ${new Date(a.deadline).toLocaleString('th-TH')}</p><div class="card" style="margin:16px 0;background:#f8fafc"><div class="muted">สถานะ</div><div style="font-size:20px;font-weight:800">${statusBadge(s.status)}</div><div style="margin-top:12px"><b>คะแนน</b><div style="font-size:36px;font-weight:900">${s.score} / ${a.maxScore}</div></div><div><b>เวลาส่ง</b><div>${new Date(s.submittedAt).toLocaleString('th-TH')}</div></div>${s.comment?`<div style="margin-top:12px"><b>ความคิดเห็นอาจารย์</b><div>${esc(s.comment)}</div></div>`:''}${s.originalName?`<div style="margin-top:12px"><b>ไฟล์ที่ส่ง</b><div class="actions"><span>${esc(s.originalName)}</span>${s.file||s.evidence?`<button class="btn gray" onclick="openFile('${esc(s.file||s.evidence)}')">👁 เปิดไฟล์</button><button class="btn gray" onclick="downloadFile('${esc(s.file||s.evidence)}')">ดาวน์โหลด</button>`:''}</div></div>`:''}</div><button class="btn" onclick="document.getElementById('modal').remove()">ปิด</button></div>`;document.body.appendChild(modal)}catch(e){toast(e.message)}}
async function openSubmit(id,type){const d=await api('/assignments');const a=d.assignments.find(x=>x.id===id);if(!a){toast('ไม่พบ Assignment');return}const modal=document.createElement('div');modal.className='modal-backdrop';modal.id='modal';modal.innerHTML=`<div class="modal"><button class="close" onclick="document.getElementById('modal').remove()">×</button><h2>${esc(a.title)}</h2><p>${esc(a.description)}</p><p><b>${esc(a.subject)}</b> · ${a.maxScore} คะแนน · Deadline ${new Date(a.deadline).toLocaleString('th-TH')}</p>${a.attachment?.url?`<div class="card" style="margin:14px 0;background:#f8fafc"><b>📎 ไฟล์โจทย์</b><div class="muted">${esc(a.attachment.originalName||'ไฟล์ประกอบ')}</div><div class="actions" style="margin-top:10px"><button type="button" class="btn" onclick="openFile('${esc(a.attachment.url)}')">👁 เปิดไฟล์โจทย์</button><button class="btn gray" onclick="downloadFile('${esc(a.attachment.url)}')">ดาวน์โหลด</button></div></div>`:''}${type==='Online'?`<form id="submitForm"><label>ไฟล์งาน<input type="file" id="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" required></label><button class="primary">Confirm Submission</button></form>`:`<form id="offlineForm"><label>Assignment Code 6 หลัก<input id="code" maxlength="6" inputmode="numeric" required placeholder="เช่น 583214"></label><label>หลักฐานการส่ง (ไม่บังคับ)<input type="file" id="evidence" accept="image/*"></label><button class="primary" id="confirm" disabled>Confirm Submission</button><p class="muted">กรุณากรอกรหัส Assignment 6 หลัก</p></form>`}</div>`;document.body.appendChild(modal);if(type==='Online')document.getElementById('submitForm').onsubmit=async e=>{e.preventDefault();const file=document.getElementById('file').files[0];if(!file){toast('กรุณาเลือกไฟล์');return}const fd=new FormData();fd.append('assignmentId',id);fd.append('file',file);try{await api('/submissions/online',{method:'POST',body:fd});modal.remove();toast('ส่งข้อมูลสำเร็จ',true);show('assignments')}catch(err){toast(err.message)}};else{const code=document.getElementById('code');const btn=document.getElementById('confirm');code.oninput=()=>btn.disabled=!/^\d{6}$/.test(code.value);document.getElementById('offlineForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData();fd.append('assignmentId',id);fd.append('code',code.value);if(document.getElementById('evidence').files[0])fd.append('evidence',document.getElementById('evidence').files[0]);try{await api('/submissions/offline',{method:'POST',body:fd});modal.remove();toast('ส่งข้อมูลสำเร็จ',true);show('assignments')}catch(err){toast(err.message)}}}}
async function generateLink(){try{const d=await api('/parent/link-code',{method:'POST'});document.getElementById('linkBox').innerHTML=`<div class="card" style="margin-top:14px;background:#f8fafc"><b>Link Code</b><div style="font-size:28px;font-weight:900;letter-spacing:2px">${d.code}</div><p class="muted">หมดอายุ ${new Date(d.expiresAt).toLocaleTimeString('th-TH')} · เปิด LINE ของผู้ปกครอง เพิ่ม STUDLY Official Account แล้วส่งรหัสนี้ในแชต เพื่อให้ Backend ตรวจสอบและขอ Parent Confirmation</p></div>`}catch(e){toast(e.message)}}
async function testLine(){try{const d=await api('/line/send-message',{method:'POST'});toast(d.message,true)}catch(e){toast(e.message)}}async function smartAlert(){try{const d=await api('/line/smart-alert',{method:'POST'});toast(d.message,true)}catch(e){toast(e.message)}}async function disconnectLine(){try{await api('/parent/disconnect',{method:'POST'});show('profile')}catch(e){toast(e.message)}}
async function loadStudentNotifyBox(targetId){
  const box=document.getElementById(targetId); if(!box)return;
  try{
    const d=await api('/notification-settings');
    const items=[
      ['newAssignment','งานใหม่'],
      ['deadlineNear','Deadline ใกล้'],
      ['overdue','งานเลยกำหนด'],
      ['aiRecommendation','AI Recommendation'],
      ['teacherGraded','Teacher ตรวจงานแล้ว']
    ];
    box.innerHTML=items.map(([key,label])=>`<label class="switch-row"><span>${label}</span><input type="checkbox" ${d.settings[key]?'checked':''} onchange="saveNotifySetting('${key}',this.checked)"><span class="switch"></span></label>`).join('');
  }catch(e){box.innerHTML=`<p class="muted">${esc(e.message)}</p>`}
}
async function loadStudentNotificationSettings(){return loadStudentNotifyBox('studentNotifySettings')}
async function saveNotifySetting(key,value){try{await api('/notification-settings',{method:'PUT',body:JSON.stringify({[key]:value})});toast(value?'เปิดการแจ้งเตือนแล้ว':'ปิดการแจ้งเตือนแล้ว',true)}catch(e){toast(e.message)}}
window.showSubject=showSubject;window.clearSubjectFilter=clearSubjectFilter;window.openResult=openResult;window.openSubmit=openSubmit;window.generateLink=generateLink;window.testLine=testLine;window.smartAlert=smartAlert;window.disconnectLine=disconnectLine;window.saveNotifySetting=saveNotifySetting;
