const express=require('express');const crypto=require('crypto');const store=require('../store');const {sessionUser}=require('./api');
const router=express.Router();
function verifySignature(req){const secret=process.env.LINE_CHANNEL_SECRET;if(!secret)return false;const sig=req.headers['x-line-signature'];if(!sig)return false;const raw=req.rawBody||Buffer.from(JSON.stringify(req.body));const hash=crypto.createHmac('sha256',secret).update(raw).digest('base64');return crypto.timingSafeEqual(Buffer.from(hash),Buffer.from(sig));}
async function linePush(to,messages){if(!process.env.LINE_CHANNEL_ACCESS_TOKEN)throw new Error('ยังไม่ได้ตั้งค่า LINE API');const r=await fetch('https://api.line.me/v2/bot/message/push',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${process.env.LINE_CHANNEL_ACCESS_TOKEN}`},body:JSON.stringify({to,messages})});if(!r.ok)throw new Error(`LINE API ${r.status}`);return true;}
router.post('/webhook',async(req,res)=>{if(process.env.LINE_CHANNEL_SECRET&&!verifySignature(req))return res.status(401).send('invalid signature');try{for(const ev of req.body.events||[]){if(ev.type==='message'&&ev.message?.type==='text'){const text=ev.message.text.trim();const db=store.read();const code=db.linkCodes.find(c=>c.code===text&&!c.used&&new Date(c.expiresAt)>new Date());if(code){const student=db.users.find(u=>u.id===code.studentId);if(!student)continue;store.update(d=>{const c=d.linkCodes.find(x=>x.code===code.code);c.used=true;d.parentConnections=d.parentConnections.filter(x=>x.studentId!==student.id);d.parentConnections.push({studentId:student.id,lineUserId:ev.source.userId,connectedAt:new Date().toISOString(),relationship:'parent',status:'PENDING_CONFIRMATION'});return d;});await linePush(ev.source.userId,[{type:'template',altText:'ยืนยันการเชื่อมต่อ STUDLY',template:{type:'confirm',text:`พบคำขอเชื่อมต่อกับบัญชีของ ${student.name} ต้องการเชื่อมต่อเป็นผู้ปกครองหรือไม่?`,actions:[{type:'post',label:'ยืนยันการเชื่อมต่อ',data:`confirm:${student.id}`},{type:'message',label:'ยกเลิก',text:'ยกเลิกการเชื่อมต่อ'}]}}]);}else if(text.startsWith('confirm:')){const studentId=text.split(':')[1];store.update(d=>{const c=d.parentConnections.find(x=>x.studentId===studentId&&x.lineUserId===ev.source.userId);if(c)c.status='CONNECTED';return d;});await linePush(ev.source.userId,[{type:'text',text:'🟢 เชื่อมต่อ STUDLY สำเร็จแล้ว'}]);}}if(ev.type==='postback'&&ev.postback?.data?.startsWith('confirm:')){const studentId=ev.postback.data.split(':')[1];store.update(d=>{const c=d.parentConnections.find(x=>x.studentId===studentId&&x.lineUserId===ev.source.userId);if(c)c.status='CONNECTED';return d;});await linePush(ev.source.userId,[{type:'text',text:'🟢 เชื่อมต่อ STUDLY สำเร็จแล้ว'}]);}}res.json({ok:true});}catch(e){console.error('LINE webhook error:',e.message);res.status(500).json({error:'Webhook processing failed'});}});
router.post('/send-message',async(req,res)=>{const auth=(req.headers.authorization||'').replace('Bearer ','');const u=sessionUser(auth);if(!u||u.role!=='student')return res.status(403).json({error:'ไม่มีสิทธิ์'});const db=store.read();const c=db.parentConnections.find(x=>x.studentId===u.id&&x.status==='CONNECTED');if(!c)return res.status(400).json({error:'ยังไม่ได้เชื่อมต่อ LINE ผู้ปกครอง'});try{await linePush(c.lineUserId,[{type:'text',text:'🎓 STUDLY\nนี่คือข้อความทดสอบจากระบบ STUDLY\nการเชื่อมต่อ LINE สำเร็จแล้ว'}]);res.json({ok:true,message:'ส่งข้อความทดสอบสำเร็จ'});}catch(e){res.status(500).json({error:'ไม่สามารถส่งข้อความได้ กรุณาตรวจสอบการตั้งค่า LINE'});}});
router.post('/test-message',async(req,res)=>{return router.handle({...req,method:'POST',url:'/send-message'},res,()=>{});});
async function sendSmartAlert(studentId){const db=store.read();const c=db.parentConnections.find(x=>x.studentId===studentId&&x.status==='CONNECTED');if(!c)throw new Error('No connected parent');const physics=db.subjects.find(s=>s.name==='Physics');await linePush(c.lineUserId,[{type:'text',text:`🔴 STUDLY Smart Alert\nแจ้งเตือนการเรียนของน้องสมชาย\nPhysics มีความเสี่ยงสูง\nคะแนนปัจจุบัน: ${physics?.score||42}%\nงานสำคัญใกล้ Deadline: 1 งาน\nแนะนำให้ช่วยน้องวางแผนการทำงาน`}]);}
router.post('/smart-alert',async(req,res)=>{const auth=(req.headers.authorization||'').replace('Bearer ','');const u=sessionUser(auth);if(!u||u.role!=='student')return res.status(403).json({error:'ไม่มีสิทธิ์'});try{await sendSmartAlert(u.id);res.json({ok:true,message:'ส่ง Smart Alert สำเร็จ'});}catch(e){res.status(500).json({error:'ไม่สามารถส่ง Smart Alert ได้ กรุณาตรวจสอบการตั้งค่า LINE'});}});
module.exports={router};
